### ISSUE TITLE
convertFonts cannot be called without a callback

### ISSUE THREAD

**Issue by tamias** [radist2s/fontconvert-tool#2]
The documentation shows examples of calling `convertFonts` without a callback:

```
fontconvert.convertFonts('./fonts-source', './fonts-out')
```

However, an error is thrown, because the code tries to call the callback without checking that one was actually passed:

```
.../fontconvert-tool/index.js:242
                callback.apply(undefined, arguments)
                         ^

TypeError: Cannot read property 'apply' of undefined

```

**Comment by radist2s** [comment]
Thank you for report. Fixed.
